backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "productos"
    # --- FIX: All lines below are indented with 2 spaces ---
    label: "Productos"
    folder: "assets/data/productos"
    create: true
    # --- FIX: Automatically creates the URL from the "Nombre" field ---
    slug: "{{slug}}"
    fields:
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Detalles", name: "details", widget: "string" }
      - { label: "Descripción", name: "body", widget: "markdown" }