backend:
  name: git-gateway
  branch: main  # ✅ ahora trabajas en main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "assets/data/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Descripción", name: "body", widget: "markdown" }
      - { label: "Imagen", name: "image", widget: "image" }
