backend:
  name: git-gateway
  branch: main

# No changes needed here, your paths are correct.
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "assets/data/productos"
    create: true
    slug: "{{slug}}" # This now works because we are adding a 'slug' field below
    fields:
      # Fields are reordered for a better user experience in the CMS
      - { label: "Título del Producto", name: "title", widget: "string" }

      # <-- ADD THIS FIELD. It is REQUIRED for the `slug` line above to work.
      - {
          label: "URL (slug)",
          name: "slug",
          widget: "string",
          hint: "Esta es la parte de la URL para el producto. Debe ser única y no tener espacios. Ej: anillo-de-oro-18k",
        }

      - { label: "Categoría", name: "categoria", widget: "string" }

      # The main image is now more clearly labeled
      - {
          label: "Imagen Principal (Thumbnail)",
          name: "image",
          widget: "image",
        }

      # <-- THIS IS THE NEW GALLERY SECTION
      - label: "Galería de Imágenes Adicionales"
        name: "images"
        widget: "list"
        hint: "Añade imágenes extra para la galería del producto."
        field: { label: "Imagen de Galería", name: "image", widget: "image" }

      # The 'details' field is kept for your product list page
      - {
          label: "Detalles (Descripción corta)",
          name: "details",
          widget: "string",
          hint: "Una frase corta que aparece en la vista de tarjetas de productos.",
        }

      - { label: "Descripción Completa", name: "body", widget: "markdown" }